runtime: go112
main: ./backend

env_variables:
  MYSQL_HOST: 35.241.81.102
  MYSQL_USER: vote2020
  MYSQL_PASSWORD: vote2020
  MYSQL_DB: vote2020
  VERNACULAR_KEY: g0v2020

handlers:
  - url: /api/.*
    script: auto

  - url: /img
    static_dir: mobile/build/img

  - url: /static
    static_dir: mobile/build/static

  - url: /(.*\.(json|ico))$
    static_files: mobile/build/\1
    upload: mobile/build/.*\.(json|ico)$

  - url: .*
    static_files: mobile/build/index.html
    upload: mobile/build/index.html

automatic_scaling:
  max_instances: 5
