basePath: '{{.BasePath}}'
definitions:
  models.Candidate:
    properties:
      age:
        type: integer
      bornIn:
        type: string
      educationalBackground:
        items:
          type: string
        type: array
      experiences:
        items:
          type: string
        type: array
      id:
        type: string
      name:
        type: string
      party:
        $ref: '#/definitions/models.PartyCard'
        type: object
      photo:
        type: string
      politics:
        type: string
    type: object
  models.CandidateCard:
    properties:
      experience:
        type: string
      id:
        type: string
      name:
        type: string
      party:
        $ref: '#/definitions/models.PartyCard'
        type: object
      photo:
        type: string
    type: object
  models.CandidateCards:
    items:
      properties:
        experience:
          type: string
        id:
          type: string
        name:
          type: string
        party:
          $ref: '#/definitions/models.PartyCard'
          type: object
        photo:
          type: string
      type: object
    type: array
  models.PartyCard:
    properties:
      emblem:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: 2020 Voting Guide Backend
  license: {}
  title: 2020 Voting Guide
  version: 0.0.1
paths:
  /candidate/{id}:
    get:
      consumes:
      - application/json
      description: get the candidate by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Candidate'
            type: object
      summary: get the candidate by id
  /candidate/{id}/record:
    get:
      consumes:
      - application/json
      description: get records of candidate by id
      parameters:
      - description: ID
        in: path
        name: id
        type: string
      responses:
        "200":
          description: record
          schema:
            type: string
      summary: get records of candidate by id
  /candidates/constituency/{constituency}:
    get:
      consumes:
      - application/json
      description: list candidates by constituency
      parameters:
      - description: Constituency
        in: path
        name: constituency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CandidateCards'
            type: object
      summary: List candidates by constituency
  /version:
    get:
      responses:
        "200":
          description: X.X.X
          schema:
            type: string
        "500":
          description: fail
      summary: 2020 Voting Guide Service Version
swagger: "2.0"
