basePath: '{{.BasePath}}'
definitions:
  models.Candidate:
    properties:
      age:
        type: integer
      bornIn:
        type: string
      educationalBackground:
        type: string
      experience:
        type: string
      id:
        type: string
      name:
        type: string
      party:
        type: string
      photo:
        type: string
      politics:
        type: string
    type: object
  models.CandidateCard:
    properties:
      constituency:
        type: string
      experience:
        type: string
      id:
        type: string
      name:
        type: string
      party:
        type: string
      photo:
        type: string
    type: object
  models.CandidateCards:
    items:
      properties:
        constituency:
          type: string
        experience:
          type: string
        id:
          type: string
        name:
          type: string
        party:
          type: string
        photo:
          type: string
      type: object
    type: array
host: '{{.Host}}'
info:
  contact: {}
  description: 2020 Voting Guide Backend
  license: {}
  title: 2020 Voting Guide
  version: 0.0.1
paths:
  /candidate/{name}:
    get:
      consumes:
      - application/json
      description: get the candidate by name
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Candidate'
            type: object
      summary: get the candidate by name
  /candidate/{name}/record:
    get:
      consumes:
      - application/json
      description: get records of candidate by name
      parameters:
      - description: Name
        in: path
        name: name
        type: string
      responses:
        "200":
          description: record
          schema:
            type: string
      summary: get records of candidate by name
  /candidates/constituency/{constituency}:
    get:
      consumes:
      - application/json
      description: list candidates by constituency
      parameters:
      - description: Constituency
        in: path
        name: constituency
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CandidateCards'
            type: object
      summary: List candidates by constituency
  /version:
    get:
      responses:
        "200":
          description: X.X.X
          schema:
            type: string
        "500":
          description: fail
      summary: 2020 Voting Guide Service Version
swagger: "2.0"
